# Generated by Django 2.2.4 on 2019-10-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intruder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intruder', models.CharField(max_length=10)),
                ('cam', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
