# Generated by Django 2.2.4 on 2019-10-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_intruder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intruder',
            name='date',
        ),
    ]
