# Generated by Django 2.2.4 on 2019-10-01 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_remove_intruder_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intruder',
        ),
    ]
