# Generated by Django 2.2.4 on 2019-10-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_delete_intruder'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
