# Generated by Django 2.2.4 on 2019-10-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_auto_20191011_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intruder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intru', models.CharField(max_length=10)),
                ('IPcam', models.CharField(max_length=10)),
                ('Time', models.CharField(max_length=30)),
                ('ImageID', models.CharField(max_length=50)),
            ],
        ),
    ]
