# Generated by Django 2.2.4 on 2019-10-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_intruder'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPcamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPcamera_name', models.CharField(max_length=10)),
                ('IPcamera_status', models.CharField(max_length=10)),
                ('IPconnect_status', models.CharField(max_length=10)),
                ('Background_status', models.CharField(max_length=10)),
                ('Time_log', models.CharField(max_length=10)),
            ],
        ),
    ]
