# Generated by Django 2.2.4 on 2019-10-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_ipcamera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errormessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorID', models.CharField(max_length=10)),
                ('errorName', models.CharField(max_length=20)),
                ('errorTime', models.CharField(max_length=20)),
                ('errorDetail', models.CharField(max_length=50)),
            ],
        ),
    ]
