# Generated by Django 2.2.4 on 2019-11-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_errormessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPnum', models.CharField(max_length=20)),
                ('IPconnect', models.CharField(max_length=5)),
                ('IP_ODconnect', models.CharField(max_length=5)),
            ],
        ),
    ]
