# Generated by Django 2.2.4 on 2019-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0012_auto_20191109_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='overviewStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Over_name', models.CharField(max_length=20)),
                ('Over_num', models.CharField(max_length=10)),
            ],
        ),
    ]
