# Generated by Django 2.2.4 on 2020-02-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0013_overviewstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_name', models.CharField(max_length=20)),
                ('daly_time', models.CharField(max_length=20)),
            ],
        ),
    ]
