# Generated by Django 2.2.4 on 2020-02-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0015_auto_20200210_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CameraNoti_name', models.CharField(max_length=20)),
                ('CameraNoti_status', models.CharField(max_length=10)),
            ],
        ),
    ]
