# Generated by Django 2.2.4 on 2020-03-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0016_camera_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='camera_notification',
        ),
    ]
