# Generated by Django 2.2.4 on 2020-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0017_delete_camera_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CameraNoti_name', models.CharField(max_length=20)),
                ('CameraNoti_status', models.CharField(max_length=10)),
            ],
        ),
    ]
